apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-jetstream-config
data:
  nats.conf: |
    jetstream {
      store_dir: "/jetstream/data"
    }

    http: 0.0.0.0:8222

    server_name: "nats-jetstream"
