apiVersion: v1
kind: Pod
metadata:
  name: natz-box
  namespace: jetstream-messaging
spec:
  containers:
    - name: natz-box
      image: synadia/nats-box:latest
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
